name: Frontend CI

on: [push]

jobs:
  eslint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps
        run: yarn install

      - name: run lint
        run: yarn lint
